<?php

namespace CodinCyco\ToDoBundle\Repository;

/**
 * globeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class globeRepository extends \Doctrine\ORM\EntityRepository
{
}
