<?php

namespace Operateur\TelecomBundle\Repository;

/**
 * SimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimRepository extends \Doctrine\ORM\EntityRepository
{
}
